version: '3.8'

services:
  api:
    build: .
    ports:
      - "8011:8011"
    env_file:
      - .env
    depends_on:
      - minio
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio
    ports:
      - "8999:8999"  # API порт
      - "9003:9003"  # Console порт
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_PORT: 8999
      MINIO_CONSOLE_PORT: 9003
    volumes:
      - minio-data:/data
    command: server --console-address ":9003" --address ":8999" /data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
  postgres_data: